#!/usr/bin/env python3
"""
Twitter/X Draft Generator
Creates optimized tweet drafts saved to vault for manual posting

Usage:
    python create_draft.py --topic "Your topic here"
    python create_draft.py --topic "AI automation" --style professional
"""

import os
import argparse
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


def generate_tweet_draft(topic: str, style: str = "engaging") -> dict:
    """Generate tweet content based on topic and style"""

    # Tweet templates based on style
    templates = {
        "engaging": {
            "format": "hook + value + cta",
            "example": "🔥 {hook}\n\n{body}\n\n{cta}\n\n{hashtags}"
        },
        "professional": {
            "format": "statement + insight + hashtags",
            "example": "{statement}\n\n💡 {insight}\n\n{hashtags}"
        },
        "casual": {
            "format": "thought + emoji",
            "example": "{thought} {emoji}\n\n{hashtags}"
        },
        "thread": {
            "format": "intro → points → conclusion",
            "example": "🧵 Thread: {topic}\n\n1/ {point1}\n\n2/ {point2}\n\n3/ {point3}"
        }
    }

    template = templates.get(style, templates["engaging"])

    # Generate draft structure
    draft = {
        "topic": topic,
        "style": style,
        "template": template["format"],
        "content": f"""[TWEET DRAFT]

Topic: {topic}
Style: {style}
Format: {template['format']}

---

📝 DRAFT CONTENT (edit as needed):

🔥 [Write attention-grabbing hook about {topic}]

[Main message about {topic} - keep it valuable]

👇 [Call to action - like, follow, comment, etc.]

#AI #Automation #Tech #Innovation

---

⚠️ CHECKLIST:
- [ ] Under 280 characters (current: ___/280)
- [ ] Hook is attention-grabbing
- [ ] Value is clear
- [ ] CTA is specific
- [ ] Hashtags are relevant (max 3-5)
- [ ] No typos

📋 COPY THE CONTENT ABOVE → PASTE IN TWITTER → POST!
""",
        "char_limit": 280,
        "created": datetime.now().isoformat()
    }

    return draft


def save_draft(draft: dict, vault_path: str = None) -> Path:
    """Save draft to vault"""
    vault = Path(vault_path or os.getenv("VAULT_PATH", "./vault"))
    drafts_dir = vault / "Social_Media" / "Twitter_Drafts"
    drafts_dir.mkdir(parents=True, exist_ok=True)

    # Create filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    slug = draft["topic"][:30].replace(" ", "_").lower()
    filename = f"TWEET_{timestamp}_{slug}.md"
    filepath = drafts_dir / filename

    # Create markdown content
    content = f"""---
type: twitter_draft
topic: {draft['topic']}
style: {draft['style']}
created: {draft['created']}
status: pending
char_limit: 280
---

{draft['content']}

---

## How to Post:

1. Copy the draft content above
2. Open Twitter/X in your browser
3. Click "Post" button
4. Paste the content
5. Review and edit if needed
6. Click "Post"
7. Move this file to /Done/ folder ✅

*Generated by AI Employee - Twitter Drafting Skill*
"""

    filepath.write_text(content, encoding="utf-8")
    return filepath


def main():
    parser = argparse.ArgumentParser(description="Generate Twitter Draft")
    parser.add_argument("--topic", required=True, help="Topic for the tweet")
    parser.add_argument("--style", default="engaging",
                       choices=["engaging", "professional", "casual", "thread"],
                       help="Tweet style")
    parser.add_argument("--vault", help="Path to vault")

    args = parser.parse_args()

    print(f"🐦 Generating Twitter draft...")
    print(f"   Topic: {args.topic}")
    print(f"   Style: {args.style}")

    draft = generate_tweet_draft(args.topic, args.style)
    filepath = save_draft(draft, args.vault)

    print(f"\n✅ Draft saved: {filepath}")
    print(f"\n{'='*50}")
    print(draft["content"])
    print(f"{'='*50}")
    print(f"\n📋 Open the file, copy content, paste in Twitter!")


if __name__ == "__main__":
    main()
