#!/usr/bin/env python3
"""
Facebook & Instagram Draft Generator
Creates optimized post drafts saved to vault for manual posting

Usage:
    python create_draft.py --platform facebook --topic "Your topic"
    python create_draft.py --platform instagram --topic "Product launch" --style promotional
"""

import os
import argparse
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


def generate_facebook_draft(topic: str, style: str = "engaging") -> dict:
    """Generate Facebook post content"""

    draft = {
        "platform": "facebook",
        "topic": topic,
        "style": style,
        "content": f"""[FACEBOOK POST DRAFT]

Topic: {topic}
Style: {style}

---

📝 DRAFT CONTENT (edit as needed):

🚀 [Attention-grabbing opening about {topic}]

[Share your main message here - Facebook allows longer posts so add value!]

[Add a personal touch or story related to {topic}]

💡 Key takeaway: [What should readers remember?]

👇 What do you think? Drop a comment below!

#AI #Business #Innovation #Technology

---

⚠️ CHECKLIST:
- [ ] Opening hooks attention
- [ ] Message is clear and valuable
- [ ] Personal/story element included
- [ ] Clear call-to-action
- [ ] Relevant hashtags (3-5)
- [ ] Image/video to attach? (recommended)

📋 COPY → PASTE IN FACEBOOK → POST!
""",
        "created": datetime.now().isoformat()
    }

    return draft


def generate_instagram_draft(topic: str, style: str = "engaging") -> dict:
    """Generate Instagram caption content"""

    draft = {
        "platform": "instagram",
        "topic": topic,
        "style": style,
        "content": f"""[INSTAGRAM CAPTION DRAFT]

Topic: {topic}
Style: {style}

---

📝 CAPTION (edit as needed):

[First line is CRUCIAL - make it scroll-stopping! ✨]

[Share value about {topic}]

[Add 2-3 line breaks for readability]

[Include a question or CTA]

.
.
.

#AI #Tech #Innovation #Business #Automation
#Growth #Entrepreneur #DigitalMarketing
#Productivity #Success

---

📸 IMAGE IDEAS:
- [ ] Product/service screenshot
- [ ] Quote graphic
- [ ] Behind-the-scenes
- [ ] Carousel (multiple images)
- [ ] Reel/Video

⚠️ CHECKLIST:
- [ ] First line hooks attention
- [ ] Line breaks for readability
- [ ] Clear CTA (comment, save, share)
- [ ] 20-30 hashtags (in comment or caption)
- [ ] Image/video ready

📋 COPY → PASTE IN INSTAGRAM → ADD IMAGE → POST!
""",
        "created": datetime.now().isoformat()
    }

    return draft


def save_draft(draft: dict, vault_path: str = None) -> Path:
    """Save draft to vault"""
    vault = Path(vault_path or os.getenv("VAULT_PATH", "./vault"))

    platform = draft["platform"].title()
    drafts_dir = vault / "Social_Media" / f"{platform}_Drafts"
    drafts_dir.mkdir(parents=True, exist_ok=True)

    # Create filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    slug = draft["topic"][:30].replace(" ", "_").lower()
    prefix = "FB" if draft["platform"] == "facebook" else "IG"
    filename = f"{prefix}_{timestamp}_{slug}.md"
    filepath = drafts_dir / filename

    # Create markdown content
    content = f"""---
type: {draft['platform']}_draft
topic: {draft['topic']}
style: {draft['style']}
created: {draft['created']}
status: pending
---

{draft['content']}

---

## How to Post:

1. Copy the draft content above
2. Open {platform} in your browser/app
3. Create new post
4. Paste the content
5. Add image/video (required for Instagram)
6. Review and edit if needed
7. Click "Post"
8. Move this file to /Done/ folder ✅

*Generated by AI Employee - {platform} Drafting Skill*
"""

    filepath.write_text(content, encoding="utf-8")
    return filepath


def main():
    parser = argparse.ArgumentParser(description="Generate Facebook/Instagram Draft")
    parser.add_argument("--platform", required=True,
                       choices=["facebook", "instagram"],
                       help="Target platform")
    parser.add_argument("--topic", required=True, help="Topic for the post")
    parser.add_argument("--style", default="engaging",
                       choices=["engaging", "promotional", "educational", "personal"],
                       help="Post style")
    parser.add_argument("--vault", help="Path to vault")

    args = parser.parse_args()

    print(f"📱 Generating {args.platform.title()} draft...")
    print(f"   Topic: {args.topic}")
    print(f"   Style: {args.style}")

    if args.platform == "facebook":
        draft = generate_facebook_draft(args.topic, args.style)
    else:
        draft = generate_instagram_draft(args.topic, args.style)

    filepath = save_draft(draft, args.vault)

    print(f"\n✅ Draft saved: {filepath}")
    print(f"\n{'='*50}")
    print(draft["content"])
    print(f"{'='*50}")
    print(f"\n📋 Open the file, copy content, paste in {args.platform.title()}!")


if __name__ == "__main__":
    main()
