# LinkedIn Post Generator - PowerShell
# Usage: .\linkedin_post.ps1 "topic here"

param(
    [string]$Topic = "weekly update"
)

$VaultPath = "D:\Side Projects\gh-hackthone\Hackathon-0\vault"
$Date = Get-Date -Format "yyyy-MM-dd"
$Slug = $Topic.ToLower() -replace '\s+', '-' | Select-String -Pattern '.{1,30}' | Select-Object -First 1
$DraftFile = "$VaultPath\Social_Media\LinkedIn_Drafts\${Date}_${Slug}.md"

Write-Host "Generating LinkedIn post about: $Topic" -ForegroundColor Cyan

# Create prompt
$Prompt = @"
You are a professional LinkedIn content creator.

Generate a LinkedIn post about: $Topic

Context:
- Read vault/Business_Goals.md for business context
- Read vault/Dashboard.md for recent activity
- This is for an AI Employee automation project

Requirements:
- 150-200 words
- Professional but conversational tone
- Include 3-5 hashtags
- Add engaging hook
- End with call-to-action
- Maximum 2 emojis

Output ONLY the post content, nothing else.
Start directly with the post.
"@

# Call Claude Code (adjust path if needed)
try {
    $PostContent = claude -p $Prompt 2>$null

    # Create draft file
    $DraftContent = @"
---
type: linkedin_draft
created: $(Get-Date -Format o)
topic: $Topic
status: ready_to_post
---

# LinkedIn Post Draft: $Topic

$PostContent

---

## Post Instructions:
1. Review and edit if needed
2. Copy post content above
3. Open LinkedIn.com
4. Paste and publish
5. Move to Social_Media/Posted/ after posting

---
*Generated by AI Employee*
"@

    $DraftContent | Out-File -FilePath $DraftFile -Encoding UTF8

    Write-Host "✅ Draft saved: $DraftFile" -ForegroundColor Green
    Write-Host ""
    Write-Host "Open in Obsidian to review!" -ForegroundColor Yellow

} catch {
    Write-Host "❌ Error: $_" -ForegroundColor Red
    Write-Host "Make sure Claude Code is installed and accessible in PATH"
}
