#!/bin/bash
# LinkedIn Post Generator - Quick Command
# Usage: ./linkedin_post.sh "topic here"

VAULT_PATH="/mnt/d/Side Projects/gh-hackthone/Hackathon-0/vault"
TOPIC="${1:-weekly update}"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H%M)
SLUG=$(echo "$TOPIC" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | cut -c1-30)

DRAFT_FILE="$VAULT_PATH/Social_Media/LinkedIn_Drafts/${DATE}_${SLUG}.md"

# Create prompt for Claude
PROMPT="You are a professional LinkedIn content creator.

Generate a LinkedIn post about: $TOPIC

Context:
- Read vault/Business_Goals.md for business context
- Read vault/Dashboard.md for recent activity
- This is for an AI Employee automation project

Requirements:
- 150-200 words
- Professional but conversational tone
- Include 3-5 hashtags
- Add engaging hook
- End with call-to-action
- Maximum 2 emojis

Output ONLY the post content, nothing else.
Start directly with the post."

# Call Claude Code
echo "Generating LinkedIn post about: $TOPIC"
cd "$VAULT_PATH"
POST_CONTENT=$(claude -p "$PROMPT" 2>/dev/null)

# Save to file
cat > "$DRAFT_FILE" <<EOF
---
type: linkedin_draft
created: $(date -Iseconds)
topic: $TOPIC
status: ready_to_post
---

# LinkedIn Post Draft: $TOPIC

$POST_CONTENT

---

## Post Instructions:
1. Review and edit if needed
2. Copy post content above
3. Open LinkedIn.com
4. Paste and publish
5. Move to Social_Media/Posted/ after posting

---
*Generated by AI Employee*
EOF

echo "✅ Draft saved: $DRAFT_FILE"
echo ""
echo "Open in Obsidian to review!"
