#!/usr/bin/env python3
"""
LinkedIn Draft Saver Script
Deterministically saves LinkedIn post drafts with proper formatting

Usage:
    python save_draft.py --vault /path/to/vault --topic "topic" --content "post content"
"""

import argparse
import sys
from pathlib import Path
from datetime import datetime


def slugify(text: str, max_length: int = 30) -> str:
    """Convert text to URL-safe slug"""
    slug = text.lower()
    slug = ''.join(c if c.isalnum() or c in ' -_' else '' for c in slug)
    slug = slug.replace(' ', '-')
    return slug[:max_length].strip('-')


def save_draft(vault_path: str, topic: str, content: str) -> Path:
    """
    Save LinkedIn draft with proper formatting

    Args:
        vault_path: Path to Obsidian vault
        topic: Post topic
        content: Post content

    Returns:
        Path to saved draft file
    """
    vault = Path(vault_path)
    drafts_dir = vault / 'Social_Media' / 'LinkedIn_Drafts'
    drafts_dir.mkdir(parents=True, exist_ok=True)

    # Generate filename
    date = datetime.now().strftime('%Y-%m-%d')
    slug = slugify(topic)
    filename = f'{date}_{slug}.md'
    filepath = drafts_dir / filename

    # Handle duplicate filenames
    counter = 1
    while filepath.exists():
        filename = f'{date}_{slug}_{counter}.md'
        filepath = drafts_dir / filename
        counter += 1

    # Create draft content
    draft_content = f"""---
type: linkedin_draft
created: {datetime.now().isoformat()}
topic: {slug}
status: ready_to_post
---

# LinkedIn Post Draft: {topic}

{content}

---

## Post Instructions:
1. Review and edit if needed
2. Copy post content above
3. Open LinkedIn.com
4. Paste and publish
5. Move to Social_Media/Posted/ after posting

---
*Generated by AI Employee - LinkedIn Drafting Skill*
"""

    # Write file
    filepath.write_text(draft_content, encoding='utf-8')

    return filepath


def main():
    parser = argparse.ArgumentParser(description='Save LinkedIn draft')
    parser.add_argument('--vault', required=True, help='Path to vault')
    parser.add_argument('--topic', required=True, help='Post topic')
    parser.add_argument('--content', required=True, help='Post content')

    args = parser.parse_args()

    try:
        filepath = save_draft(args.vault, args.topic, args.content)
        print(f'✅ Draft saved: {filepath}')
        return 0
    except Exception as e:
        print(f'❌ Error: {e}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
